# Задача на 6-ом шаге урока

**🪢 Пишем categorical_transformer. 🤖**

Задача:

*   При помощи sklearn.Pipelines напишите свой categorical_transformer, который принимает на вход pd.DataFrame

*   Состоящий только из категориальных признаков

*   Заполняет пропуски строкой 'Unknown', а потом делает one hot encoding.

Примечание: Не нужно писать это руками, воспользуйтесь трансформерами из sklearn.impute и sklearn.preprocessing.

*Для отладки решения можно использовать следующий датасет:*

In [11]:
import pandas as pd

data_root = "../data/"
data = pd.read_csv(data_root + 'quickstart_train.csv')
data.head()

,car_id,model,car_type,fuel_type,car_rating,year_to_start,riders,year_to_work,target_reg,target_class,mean_rating,distance_sum,rating_min,speed_max,user_ride_quality_median,deviation_normal_count,user_uniq
0,y13744087j,Kia Rio X-line,economy,petrol,3.78,2015,76163,2021,108.53,another_bug,4.737759,1.214131e+07,0.1,180.855726,0.023174,174,170
1,O41613818T,VW Polo VI,economy,petrol,3.90,2015,78218,2021,35.20,electro_bug,4.480517,1.803909e+07,0.0,187.862734,12.306011,174,174
2,d-2109686j,Renault Sandero,standart,petrol,6.30,2012,23340,2017,38.62,gear_stick,4.768391,1.588366e+07,0.1,102.382857,2.513319,174,173
3,u29695600e,Mercedes-Benz GLC,business,petrol,4.04,2011,1263,2020,30.34,engine_fuel,3.880920,1.651883e+07,0.1,172.793237,-5.029476,174,170
4,N-8915870N,Renault Sandero,standart,petrol,4.70,2012,26428,2017,30.45,engine_fuel,4.181149,1.398317e+07,0.1,203.462289,-14.260456,174,171

Решение:

In [12]:
categorical_features = data.select_dtypes(exclude='number').columns
categorical_features

Index(['car_id', 'model', 'car_type', 'fuel_type', 'target_class'], dtype='object')

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='constant', fill_value='Unknown')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))])

data_pred = categorical_transformer.fit_transform(data[categorical_features])

# Задача на 7-ом шаге урока

🧵 Пишем numerical_transformer 🤖

Задача:

* Напишите свой numerical_transformer, который принимает на вход pd.DataFrame, состоящий только из численных признаков.

* Он должен заполнить пропуски медианой, потом нормализовать данные с помощью MinMaxScaler

* отобрать топ-5 признаков с наибольшим
значением функции [ANOVA F-value](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.f_classif.html).

Примечание: Не нужно писать это руками, воспользуйтесь трансформерами из sklearn.

*Для отладки решения можно использовать следующий датасет:*

In [15]:
import pandas as pd

data_root = "../data/"
data = pd.read_csv(data_root + 'quickstart_train.csv')
data.head()

,car_id,model,car_type,fuel_type,car_rating,year_to_start,riders,year_to_work,target_reg,target_class,mean_rating,distance_sum,rating_min,speed_max,user_ride_quality_median,deviation_normal_count,user_uniq
0,y13744087j,Kia Rio X-line,economy,petrol,3.78,2015,76163,2021,108.53,another_bug,4.737759,1.214131e+07,0.1,180.855726,0.023174,174,170
1,O41613818T,VW Polo VI,economy,petrol,3.90,2015,78218,2021,35.20,electro_bug,4.480517,1.803909e+07,0.0,187.862734,12.306011,174,174
2,d-2109686j,Renault Sandero,standart,petrol,6.30,2012,23340,2017,38.62,gear_stick,4.768391,1.588366e+07,0.1,102.382857,2.513319,174,173
3,u29695600e,Mercedes-Benz GLC,business,petrol,4.04,2011,1263,2020,30.34,engine_fuel,3.880920,1.651883e+07,0.1,172.793237,-5.029476,174,170
4,N-8915870N,Renault Sandero,standart,petrol,4.70,2012,26428,2017,30.45,engine_fuel,4.181149,1.398317e+07,0.1,203.462289,-14.260456,174,171

Решение:

In [20]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import SelectKBest, f_classif

numerical_features = data.select_dtypes(include='number').columns

numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', MinMaxScaler()),
    ('feature_selector', SelectKBest(score_func=f_classif, k=5))
])

data_pred = numerical_transformer.fit_transform(
    data[numerical_features],
    data['target_reg'])

c:\Users\Pong\anaconda3\envs\ml\Lib\site-packages\sklearn\feature_selection\_univariate_selection.py:111: UserWarning: Features [ 4 10] are constant.
  warnings.warn("Features %s are constant." % constant_features_idx, UserWarning)
c:\Users\Pong\anaconda3\envs\ml\Lib\site-packages\sklearn\feature_selection\_univariate_selection.py:112: RuntimeWarning: divide by zero encountered in divide
  f = msb / msw
c:\Users\Pong\anaconda3\envs\ml\Lib\site-packages\sklearn\feature_selection\_univariate_selection.py:112: RuntimeWarning: invalid value encountered in divide
  f = msb / msw

# Задача на 8-ом шаге урока

**🧳 Пишем data_transformer**

Задача:

*  Объедините предыдущие два шага вместе чтобы выполнялось следующее

*  на numerical_features ваш трансформер вызывал numerical_transformer

*  на categorical_features использовал categorical_transformer.

Примечание:  categorical_transformer и numerical_transformer считайте уже объявленными.

*Решение тестируется на тех же данных, что и предыдуще задачи - используются  трансформеры из предыдущих задач на 6-ом и 7-ом уроке*

Решение:

In [21]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.compose import ColumnTransformer

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='constant', fill_value='Unknown')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))])

numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', MinMaxScaler()),
    ('feature_selector', SelectKBest(score_func=f_classif, k=5))
])

data_transformer = ColumnTransformer(transformers=[
    ('numerical', numerical_transformer, numerical_features),
    ('categorical', categorical_transformer, categorical_features)])

data_pred = data_transformer.fit_transform(data, data['target_reg'])

c:\Users\Pong\anaconda3\envs\ml\Lib\site-packages\sklearn\feature_selection\_univariate_selection.py:111: UserWarning: Features [ 4 10] are constant.
  warnings.warn("Features %s are constant." % constant_features_idx, UserWarning)
c:\Users\Pong\anaconda3\envs\ml\Lib\site-packages\sklearn\feature_selection\_univariate_selection.py:112: RuntimeWarning: divide by zero encountered in divide
  f = msb / msw
c:\Users\Pong\anaconda3\envs\ml\Lib\site-packages\sklearn\feature_selection\_univariate_selection.py:112: RuntimeWarning: invalid value encountered in divide
  f = msb / msw

# Задача на 9-ом шаге урока

**🌂 Пишем свой классификатор**

Задача:

* Написать свой ансамбль по приведенной ниже структуре
<center> <img src = https://ucarecdn.com/94fb93eb-b945-4cdf-900f-6741c1b0aaa4/> </center>

*   В качестве final_estimator используй LogisticRegression()

Примечание: ColumnTransformer уже объявлен и лежит в переменной data_transofmer. Список моделей вы можете найти в словаре в коде (их объявлять и импортировать не нужно).

*Для тестирования решения можно использовать data_transformer из прошлой задачи*

Решение:

In [32]:
from sklearn.pipeline import make_pipeline

from sklearn.ensemble import RandomForestClassifier, StackingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from sklearn.linear_model import LogisticRegression

random_forest_model = RandomForestClassifier()
xgb_model = XGBClassifier()
lgbm_model = LGBMClassifier()
cat_model = CatBoostClassifier()

models = {'random_forest': random_forest_model,
          'xgboost': xgb_model,
          'lightgbm': lgbm_model,
          'catboost': cat_model}

# Создаем пайплайны для Random Forest и XGBoost с data_transformer
rf_pipeline = Pipeline(steps=[('preprocessor', data_transformer),
                              ('model', models['random_forest'])])

xgb_pipeline = Pipeline(steps=[('preprocessor', data_transformer),
                               ('model', models['xgboost'])])

# Объединяем все в StackingClassifier
stacking_classifier = StackingClassifier(
    estimators=[
        ('random_forest', rf_pipeline),
        ('xgboost', xgb_pipeline),
        ('lightgbm', models['lightgbm']),
        ('catboost', models['catboost'])
    ],
    final_estimator=LogisticRegression())

# Задача на 10-ом шаге урока

**🧶 Hard*. Пишем свой text_transformer 🤖**

Задача:



* Необходимо реализовать кастомный text_transformer, который можно будет встраивать в sklearn.Pipelines(). Подробно про то, как реализовать свой трансформер, вы можете прочитать [здесь](https://towardsdatascience.com/pipelines-custom-transformers-in-scikit-learn-the-step-by-step-guide-with-python-code-4a7d9b068156).


*   трансформер должен работать с текстовыми столбцами и делать следующие преобразования:
1. Удалять из текста стоп-слова, которые задаются списком в параметрах трансформера (сравнение нужно проводить до нормализации).
2. Нормализовать слова при помощи get_normal_string(). То есть каждое слово нужно заменить на get_normal_string(word) для всех слов в тексте.
3. Cчитайте, что слова разделены пробелами.

*Ваш код будет тестироваться вот таким небольшим пайплайном (можете его использовать, чтобы отлаживаться локально):*

In [ ]:
data = pd.DataFrame({'text': ['текст 1', 'текст 2']}) # это для примера

text_transformers = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy='constant', fill_value='')),
    ("scaler", TextTransformer(stop_words_list))
])

text_transformers.fit_transform(data[['text']])

array([['текст 1'],
       ['текст 2']], dtype=object)

Решение:

In [ ]:
import sklearn

# TextTransformer definition