# Задача на 4-ом шаге урока

**🤜 Универсальный ужиматель 🤛**

In [9]:
import pandas as pd
import numpy as np

В ноутбуке этого урока мы реализовали функцию reduce_mem_usage

In [10]:
def reduce_mem_usage(df):
    """ iterate through all the columns of a dataframe and modify the data type
        to reduce memory usage.
    """
    start_mem = df.memory_usage().sum() / 1024**2
    print('Memory usage of dataframe is {:.2f} MB'.format(start_mem))

    for col in df.columns:
        col_type = df[col].dtype.name

        if col_type not in ['object', 'category', 'datetime64[ns, UTC]']:
            c_min = df[col].min()
            c_max = df[col].max()
            if str(col_type)[:3] == 'int':
                if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:
                    df[col] = df[col].astype(np.int8)
                elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
                    df[col] = df[col].astype(np.int16)
                elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
                    df[col] = df[col].astype(np.int32)
                elif c_min > np.iinfo(np.int64).min and c_max < np.iinfo(np.int64).max:
                    df[col] = df[col].astype(np.int64)
            else:
                if c_min > np.finfo(np.float16).min and c_max < np.finfo(np.float16).max:
                    df[col] = df[col].astype(np.float16)
                elif c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
                    df[col] = df[col].astype(np.float32)
                else:
                    df[col] = df[col].astype(np.float64)

    end_mem = df.memory_usage().sum() / 1024**2
    print('Memory usage after optimization is: {:.2f} MB'.format(end_mem))
    print('Decreased by {:.1f}%'.format(100 * (start_mem - end_mem) / start_mem))

    return df

🧠 Задача: Добавьте в функцию reduce_mem_usage возможность оптимизации категориальных признаков (названия этих колонок передаются в cat_cols в аргументах функции). Про оптимизацию хранения категориальных признаков мы рассказывали в ноутбуке к уроку.

In [11]:
def reduce_mem_usage(df, cat_cols=[]):
    """ iterate through all the columns of a dataframe and modify the data type
        to reduce memory usage.
    """
    start_mem = df.memory_usage().sum() / 1024**2
    # print('Memory usage of dataframe is {:.2f} MB'.format(start_mem))

    for col in df.columns:
        col_type = df[col].dtype.name

        if col_type not in ['object', 'category', 'datetime64[ns, UTC]']:
            c_min = df[col].min()
            c_max = df[col].max()
            if str(col_type)[:3] == 'int':
                if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:
                    df[col] = df[col].astype(np.int8)
                elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
                    df[col] = df[col].astype(np.int16)
                elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
                    df[col] = df[col].astype(np.int32)
                elif c_min > np.iinfo(np.int64).min and c_max < np.iinfo(np.int64).max:
                    df[col] = df[col].astype(np.int64)
            else:
                if c_min > np.finfo(np.float16).min and c_max < np.finfo(np.float16).max:
                    df[col] = df[col].astype(np.float16)
                elif c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
                    df[col] = df[col].astype(np.float32)
                else:
                    df[col] = df[col].astype(np.float64)

    for col in df.columns:
        if col in cat_cols:
            df[col] = df[col].astype('category')

    # end_mem = df.memory_usage().sum() / 1024**2
    # print('Memory usage after optimization is: {:.2f} MB'.format(end_mem))
    # print('Decreased by {:.1f}%'.format(100 * (start_mem - end_mem) / start_mem))

    return df

In [12]:
df = pd.read_csv('../data/demo_car_train.csv')
display(df.head())
df.info(memory_usage='deep')

,car_id,model,car_type,fuel_type,car_rating,year_to_start,riders,year_to_work,target_1,target_2
0,e-1431476C,Renault Kaptur,standart,petrol,4.84,2014,3856,2017,2,gear_stick
1,L-6578341x,Renault Sandero,standart,petrol,4.84,2011,54093,2018,0,engine_check
2,i11115813c,Skoda Rapid,economy,petrol,4.16,2015,16214,2017,0,electro_bug
3,w-1250035f,Kia Rio X-line,economy,petrol,5.30,2015,16948,2017,1,wheel_shake
4,E-3430793T,Smart Coupe,economy,petrol,4.54,2015,20430,2014,1,break_bug

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   car_id         1000 non-null   object
 1   model          1000 non-null   object
 2   car_type       1000 non-null   object
 3   fuel_type      1000 non-null   object
 4   car_rating     1000 non-null   float64
 5   year_to_start  1000 non-null   int64
 6   riders         1000 non-null   int64
 7   year_to_work   1000 non-null   int64
 8   target_1       1000 non-null   int64
 9   target_2       1000 non-null   object
dtypes: float64(1), int64(4), object(5)
memory usage: 323.8 KB

In [13]:
cat_cols = ['model', 'car_type', 'fuel_type', 'target_2']
df_new = reduce_mem_usage(df=df, cat_cols=cat_cols)
df_new.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   car_id         1000 non-null   object
 1   model          1000 non-null   category
 2   car_type       1000 non-null   category
 3   fuel_type      1000 non-null   category
 4   car_rating     1000 non-null   float16
 5   year_to_start  1000 non-null   int16
 6   riders         1000 non-null   int32
 7   year_to_work   1000 non-null   int16
 8   target_1       1000 non-null   int8
 9   target_2       1000 non-null   category
dtypes: category(4), float16(1), int16(2), int32(1), int8(1), object(1)
memory usage: 76.4 KB

# Задача на 5-ом шаге урока

**Генераторы**

Напишите генератор, который принимает массив натуральных чисел и максимально возможное число в нем, а потом на каждой итерации возвращает OHE следующего элемента в массиве. Возвращаемый массив должен быть размерности (max_class + 1,). <br>
Примечание: OHE (one hot encoding) - это способ преобразования одного числа в вектор (часто используется для кодировки классов). <br>
Во время него, вы числу x сопоставляете массив длины max_len, в которой на позиции x стоит 1, а на остальных позициях 0.

In [14]:
import numpy as np

def ohe_generator(numbers, max_class):
    for num in numbers:
        # Создаём нулевой вектор длины max_class + 1
        ohe_vector = np.zeros(max_class + 1, dtype=int)
        # Устанавливаем 1 на позиции num
        ohe_vector[num] = 1

        yield ohe_vector

gen = ohe_generator([1, 3, 4], 5)

print(next(gen))
print(next(gen))
print(next(gen))

[0 1 0 0 0 0]
[0 0 0 1 0 0]
[0 0 0 0 1 0]

# Задача на 8-ом шаге урока

**🔎 Метод np.where()**

Датасет для тестирования

In [15]:
import pandas as pd
import numpy as np
path = '../data/car_info_2.csv'
df_cars = pd.read_csv(path)
df_cars.sample(5)

,car_type,fuel_type,car_rating,year_to_start,riders,car_id,model,target_class,year_to_work,target_reg
1090,economy,petrol,4.70,2016,106000,D82568273x,Smart ForFour,gear_stick,2022,26.620602
1821,economy,petrol,2.90,2015,77581,f80644426f,Smart ForTwo,wheel_shake,2018,35.085172
1324,economy,petrol,4.98,2012,20532,S-7961176I,VW Polo,engine_overheat,2018,26.154882
872,standart,petrol,5.22,2013,42956,u-1715408i,Renault Kaptur,engine_check,2016,46.379002
4222,economy,petrol,4.96,2014,57157,w-2010482q,VW Tiguan,engine_overheat,2019,36.006536

Напишите функцию, которая возвращает car_id, если данная строка датафрейма удовлетворяет условию, иначе -1.

Условие: Либо year_to_start < 2015 и тип машины business, либо ее рейтинг строго больше 3, и ее модель - это одна из ['Hyundai Solaris', 'Smart ForFour', 'Renault Kaptur', 'Renault Sandero'].

In [16]:
%%timeit
models = np.array(['Hyundai Solaris', 'Smart ForFour', 'Renault Kaptur', 'Renault Sandero'])

def get_where(df):
    # Векторизованные условия
    mask1 = (df['year_to_start'].values < 2015) & (df['car_type'].values == 'business')
    mask2 = (df['car_rating'].values > 3) & np.isin(df['model'].values, models)
    # Возвращаем результат через np.where
    return np.where(mask1 | mask2, df['car_id'].values, -1)

get_where(df_cars)

214 μs ± 2.07 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [17]:
def get_where(df_cars):
    # Конвертируем DataFrame в NumPy массивы для ускорения
    year_to_start = df_cars['year_to_start'].values
    car_type = df_cars['car_type'].values
    car_rating = df_cars['car_rating'].values
    model = df_cars['model'].values
    car_id = df_cars['car_id'].values
    
    # Условие 1
    condition1 = (year_to_start < 2015) & (car_type == 'business')

    # Условие 2
    target_models = np.isin(model, ['Hyundai Solaris', 'Smart ForFour', 'Renault Kaptur', 'Renault Sandero'])
    condition2 = (car_rating > 3) & target_models

    # Комбинируем условия
    mask = condition1 | condition2

    # Возвращаем car_id, если условие истинно, иначе -1
    return np.where(mask, car_id, -1)

get_where(df_cars)

array([-1, 'N-1530212S', -1, ..., 'x-1331529J', -1, -1], dtype=object)

# Задача на 10-ом шаге урока

**🍢 Векторизация**

In [18]:
import pandas as pd

path = '../data/car_info_3.csv'
df_cars = pd.read_csv(path)
df_cars.head()

,car_type,fuel_type,car_rating,year_to_start,riders,car_id,model,target_class,year_to_work,target_reg
0,economy,petrol,4.80,2013,42269,P17494612l,Skoda Rapid,engine_overheat,2019,46.650719
1,standart,petrol,4.32,2015,90014,N-1530212S,Renault Sandero,electro_bug,2016,34.377312
2,economy,petrol,4.46,2015,82684,B-1154399t,Smart ForTwo,break_bug,2017,39.157169
3,economy,petrol,3.78,2015,76163,y13744087j,Kia Rio X-line,another_bug,2021,108.533913
4,economy,petrol,2.80,2014,68833,F12725233R,Smart ForFour,gear_stick,2021,41.626137

Дана функция

In [19]:
def f(x):
    if 'Audi' == x['model']:
        if x['car_rating'] > 3:
            return 0
        else:
            if x['fuel_type'] == 'petrol':
                return 1
            return np.nan
    elif x['year_to_start'] in [2015, 2016, 2017] or x['car_rating'] > 4:
        return round(x['car_rating'] - 4.5, 3) * 10
    else:
        return 3

необходимо объявить векторизованную версию этой функции и запишите ее в переменную vectfunc. Для тестирования используется код:

In [20]:
import numpy as np

def func(car_rating, model, year_to_start, fuel_type):
    if 'Audi' == model:
        if car_rating > 3:
            return 0
        else:
            if fuel_type == 'petrol':
                return 1
            return np.nan
    elif year_to_start in [2015, 2016, 2017] or car_rating > 4:
        return round(car_rating - 4.5, 3) * 10
    else:
        return 3
        
vectfunc = np.vectorize(func, otypes=[float])

Решение

# Задача на 11-ом шаге урока

**🚦 Mетод np.select()**

У вас есть датафрейм df_cars

In [21]:
import pandas as pd
import numpy as np


path = '../data/car_info_3.csv'
df_cars = pd.read_csv(path)
df_cars.head()

,car_type,fuel_type,car_rating,year_to_start,riders,car_id,model,target_class,year_to_work,target_reg
0,economy,petrol,4.80,2013,42269,P17494612l,Skoda Rapid,engine_overheat,2019,46.650719
1,standart,petrol,4.32,2015,90014,N-1530212S,Renault Sandero,electro_bug,2016,34.377312
2,economy,petrol,4.46,2015,82684,B-1154399t,Smart ForTwo,break_bug,2017,39.157169
3,economy,petrol,3.78,2015,76163,y13744087j,Kia Rio X-line,another_bug,2021,108.533913
4,economy,petrol,2.80,2014,68833,F12725233R,Smart ForFour,gear_stick,2021,41.626137

Напишите conditions, choices и default_value, которые нужно будет использовать в np.select(), чтобы посчитать следующую функцию:

In [22]:
def f(x):
    if 'Audi' == x['model']:
        if x['car_rating'] > 3:
            return 0
        else:
            if x['fuel_type'] == 'petrol':
                return 1
            return np.nan
    elif x['year_to_start'] in [2015, 2016, 2017] or x['car_rating'] > 4:
        return round(x['car_rating'] - 4.5, 3) * 10
    else:
        return 3

Для проверки будет использоваться следующий код:

In [23]:
conditions = [
    (df_cars['model'] == 'Audi' ) & (df_cars['car_rating'] > 3),
    (df_cars['model'] == 'Audi' ) & (df_cars['fuel_type'] == 'petrol'),
    (df_cars['year_to_start'].isin([2015, 2016, 2017])) | (df_cars['car_rating'] > 4),
]

choices = [0, 1, round(df_cars['car_rating'] - 4.5, 3) * 10]

preds = np.select(conditions, choices, default=3)

In [ ]:
# У вас есть датафрейм df_cars, в котором есть два столбца: int_model и target_reg. 



# Задача: Написать функцию, которая для каждой группы (по int_model) 
# будет считать среднее, сумму, минимум и кол-во элементов в группе. 
# Для подсчета данных значений не используйте pd.groupby(), а используйте векторизацию через numpy.

# Функция должна возвращать датафрейм в следующем формате:

# Подсказка 1
# Кол-во, сумму и среднее можно посчитать при помощи np.bincount.

# Подсказка 2
# Минимум можно посчитать при помощи np.minimum.reduceat.

In [ ]:
import numpy as np
import pandas as pd

def fast_groupby(df_cars):
    # Извлекаем значения столбцов
    int_model = df_cars['int_model'].values
    target_reg = df_cars['target_reg'].values

    # Получаем уникальные группы и индексы групп для каждой строки
    unique_groups, group_idx = np.unique(int_model, return_inverse=True)
    n_groups = len(unique_groups)

    # 1. Количество элементов в каждой группе
    count_values = np.bincount(group_idx)

    # 2. Сумма target_reg по группам
    sum_values = np.bincount(group_idx, weights=target_reg)

    # 3. Среднее (сумма / количество)
    mean_values = sum_values / count_values

    # 4. Минимум по группам — через reduceat
    # Сортируем индексы по группам
    sorted_order = np.argsort(int_model)
    sorted_target = target_reg[sorted_order]
    sorted_group_idx = group_idx[sorted_order]

    # Находим границы групп
    split_indices = np.r_[0, np.where(np.diff(sorted_group_idx))[0] + 1]

    # Применяем minimum.reduceat для поиска минимума в каждой группе
    min_values = np.minimum.reduceat(sorted_target, split_indices)

    # Формируем результат
    res = pd.DataFrame({
        'int_model': unique_groups,
        'min': min_values,
        'sum': sum_values,
        'count': count_values,
        'mean': mean_values
    })

    return res