# Задача на 4-ом шаге урока

**🤜 Универсальный ужиматель 🤛**

In [1]:
import pandas as pd
import numpy as np

В ноутбуке этого урока мы реализовали функцию reduce_mem_usage

In [2]:
def reduce_mem_usage(df):
    """ iterate through all the columns of a dataframe and modify the data type
        to reduce memory usage.
    """
    start_mem = df.memory_usage().sum() / 1024**2
    print('Memory usage of dataframe is {:.2f} MB'.format(start_mem))

    for col in df.columns:
        col_type = df[col].dtype.name

        if col_type not in ['object', 'category', 'datetime64[ns, UTC]']:
            c_min = df[col].min()
            c_max = df[col].max()
            if str(col_type)[:3] == 'int':
                if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:
                    df[col] = df[col].astype(np.int8)
                elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
                    df[col] = df[col].astype(np.int16)
                elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
                    df[col] = df[col].astype(np.int32)
                elif c_min > np.iinfo(np.int64).min and c_max < np.iinfo(np.int64).max:
                    df[col] = df[col].astype(np.int64)
            else:
                if c_min > np.finfo(np.float16).min and c_max < np.finfo(np.float16).max:
                    df[col] = df[col].astype(np.float16)
                elif c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
                    df[col] = df[col].astype(np.float32)
                else:
                    df[col] = df[col].astype(np.float64)

    end_mem = df.memory_usage().sum() / 1024**2
    print('Memory usage after optimization is: {:.2f} MB'.format(end_mem))
    print('Decreased by {:.1f}%'.format(100 * (start_mem - end_mem) / start_mem))

    return df

🧠 Задача: Добавьте в функцию reduce_mem_usage возможность оптимизации категориальных признаков (названия этих колонок передаются в cat_cols в аргументах функции). Про оптимизацию хранения категориальных признаков мы рассказывали в ноутбуке к уроку.

In [16]:
def reduce_mem_usage(df, cat_cols=[]):
    """ iterate through all the columns of a dataframe and modify the data type
        to reduce memory usage.
    """
    start_mem = df.memory_usage().sum() / 1024**2
    # print('Memory usage of dataframe is {:.2f} MB'.format(start_mem))

    for col in df.columns:
        col_type = df[col].dtype.name

        if col_type not in ['object', 'category', 'datetime64[ns, UTC]']:
            c_min = df[col].min()
            c_max = df[col].max()
            if str(col_type)[:3] == 'int':
                if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:
                    df[col] = df[col].astype(np.int8)
                elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
                    df[col] = df[col].astype(np.int16)
                elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
                    df[col] = df[col].astype(np.int32)
                elif c_min > np.iinfo(np.int64).min and c_max < np.iinfo(np.int64).max:
                    df[col] = df[col].astype(np.int64)
            else:
                if c_min > np.finfo(np.float16).min and c_max < np.finfo(np.float16).max:
                    df[col] = df[col].astype(np.float16)
                elif c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
                    df[col] = df[col].astype(np.float32)
                else:
                    df[col] = df[col].astype(np.float64)

    for col in df.columns:
        if col in cat_cols:
            df[col] = df[col].astype('category')

    # end_mem = df.memory_usage().sum() / 1024**2
    # print('Memory usage after optimization is: {:.2f} MB'.format(end_mem))
    # print('Decreased by {:.1f}%'.format(100 * (start_mem - end_mem) / start_mem))

    return df

In [17]:
df = pd.read_csv('../data/demo_car_train.csv')
display(df.head())
df.info(memory_usage='deep')

,car_id,model,car_type,fuel_type,car_rating,year_to_start,riders,year_to_work,target_1,target_2
0,e-1431476C,Renault Kaptur,standart,petrol,4.84,2014,3856,2017,2,gear_stick
1,L-6578341x,Renault Sandero,standart,petrol,4.84,2011,54093,2018,0,engine_check
2,i11115813c,Skoda Rapid,economy,petrol,4.16,2015,16214,2017,0,electro_bug
3,w-1250035f,Kia Rio X-line,economy,petrol,5.30,2015,16948,2017,1,wheel_shake
4,E-3430793T,Smart Coupe,economy,petrol,4.54,2015,20430,2014,1,break_bug

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   car_id         1000 non-null   object
 1   model          1000 non-null   object
 2   car_type       1000 non-null   object
 3   fuel_type      1000 non-null   object
 4   car_rating     1000 non-null   float64
 5   year_to_start  1000 non-null   int64
 6   riders         1000 non-null   int64
 7   year_to_work   1000 non-null   int64
 8   target_1       1000 non-null   int64
 9   target_2       1000 non-null   object
dtypes: float64(1), int64(4), object(5)
memory usage: 323.8 KB

In [18]:
cat_cols = ['model', 'car_type', 'fuel_type', 'target_2']
df_new = reduce_mem_usage(df=df, cat_cols=cat_cols)
df_new.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   car_id         1000 non-null   object
 1   model          1000 non-null   category
 2   car_type       1000 non-null   category
 3   fuel_type      1000 non-null   category
 4   car_rating     1000 non-null   float16
 5   year_to_start  1000 non-null   int16
 6   riders         1000 non-null   int32
 7   year_to_work   1000 non-null   int16
 8   target_1       1000 non-null   int8
 9   target_2       1000 non-null   category
dtypes: category(4), float16(1), int16(2), int32(1), int8(1), object(1)
memory usage: 76.4 KB

# Задача на 5-ом шаге урока

**Генераторы**

Напишите генератор, который принимает массив натуральных чисел и максимально возможное число в нем, а потом на каждой итерации возвращает OHE следующего элемента в массиве. Возвращаемый массив должен быть размерности (max_class + 1,). <br>
Примечание: OHE (one hot encoding) - это способ преобразования одного числа в вектор (часто используется для кодировки классов). <br>
Во время него, вы числу x сопоставляете массив длины max_len, в которой на позиции x стоит 1, а на остальных позициях 0.

In [26]:
import numpy as np

def ohe_generator(numbers, max_class):
    for num in numbers:
        # Создаём нулевой вектор длины max_class + 1
        ohe_vector = np.zeros(max_class + 1, dtype=int)
        # Устанавливаем 1 на позиции num
        ohe_vector[num] = 1

        yield ohe_vector

gen = ohe_generator([1, 3, 4], 5)

print(next(gen))
print(next(gen))
print(next(gen))

[0 1 0 0 0 0]
[0 0 0 1 0 0]
[0 0 0 0 1 0]

# Задача на 8-ом шаге урока

**🔎 Метод np.where()**

Датасет для тестирования

In [29]:
import pandas as pd
path = '../data/car_info_2.csv'
df_cars = pd.read_csv(path)
df_cars.sample(5)

,car_type,fuel_type,car_rating,year_to_start,riders,car_id,model,target_class,year_to_work,target_reg
2646,economy,petrol,6.34,2015,82698,q-1487182h,VW Tiguan,wheel_shake,2018,32.090177
697,standart,petrol,5.16,2015,89470,W-6742818R,Renault Kaptur,engine_check,2017,55.079294
1435,economy,petrol,5.08,2014,64904,I-9335565Q,Smart ForFour,gear_stick,2016,31.184948
2429,standart,petrol,4.40,2013,41512,v10840367M,Kia Sportage,engine_ignition,2022,56.399355
2264,economy,petrol,4.76,2011,3642,M21428480q,Hyundai Solaris,another_bug,2017,74.472067

Напишите функцию, которая возвращает car_id, если данная строка датафрейма удовлетворяет условию, иначе -1.

Условие: Либо year_to_start < 2015 и тип машины business, либо ее рейтинг строго больше 3, и ее модель - это одна из ['Hyundai Solaris', 'Smart ForFour', 'Renault Kaptur', 'Renault Sandero'].

In [ ]:
def get_where(df_cars):
    # your code here

# Задача на 10-ом шаге урока

**🍢 Векторизация**

Дана функция

In [ ]:
def f(x):
    if 'Audi' == x['model']:
        if x['car_rating'] > 3:
            return 0
        else:
            if x['fuel_type'] == 'petrol':
                return 1
            return np.nan
    elif x['year_to_start'] in [2015, 2016, 2017] or x['car_rating'] > 4:
        return round(x['car_rating'] - 4.5, 3) * 10
    else:
        return 3

In [ ]:
import pandas as pd

path = 'https://raw.githubusercontent.com/a-milenkin/Competitive_Data_Science/main/data/car_info.csv'
df_cars = pd.read_csv(path)

необходимо объявить векторизованную версию этой функции и запишите ее в переменную vectfunc. Для тестирования используется код:

In [ ]:
preds = vectfunc(df_cars['car_rating'],
                 df_cars['model'],
                 df_cars['year_to_start'],
                 df_cars['fuel_type'])

Решение

In [ ]:
import numpy as np

vectfunc = #your code

# Задача на 11-ом шаге урока

**🚦 Mетод np.select()**

У вас есть датафрейм df_cars

In [ ]:
import pandas as pd
import numpy as np


path = 'https://raw.githubusercontent.com/a-milenkin/Competitive_Data_Science/main/data/car_info.csv'
df_cars = pd.read_csv(path)

Напишите conditions, choices и default_value, которые нужно будет использовать в np.select(), чтобы посчитать следующую функцию:

In [ ]:
def f(x):
    if 'Audi' == x['model']:
        if x['car_rating'] > 3:
            return 0
        else:
            if x['fuel_type'] == 'petrol':
                return 1
            return np.nan
    elif x['year_to_start'] in [2015, 2016, 2017] or x['car_rating'] > 4:
        return round(x['car_rating'] - 4.5, 3) * 10
    else:
        return 3

Для проверки будет использоваться следующий код:

In [ ]:
preds = np.select(conditions, choices, default=default_value)

Решение

In [ ]:
import numpy as np

conditions = #your code
choices = #your code
default_value = #your code